### ISSUE TITLE
socket.timeout error

### ISSUE THREAD

**Issue by terooatt** [ComputationalSystemsBiology/ExoProfiler#1]
Hi I am trying to run the first script of the Exoprofiler software and I get the following problem. I didn't have this issue this morning.

[u0643357@hci-alta Exoprofiler_project]$ nohup /home/BioApps/ExoProfiler/20150821/00_matrixScanWS/matrixScanWS.py -b input_ctcf.bed --genome hg19 --matrix_file matrix.ctcf.transfac --uth_pval 0.001 -o CTCF-Exoprofiler_file &> nohup.out &

[u0643357@hci-alta Exoprofiler_project]$ tail -F nohup.out 
nohup: ignoring input
Traceback (most recent call last):
  File "/home/BioApps/ExoProfiler/20150821/00_matrixScanWS/matrixScanWS.py", line 305, in <module>
    fasta_content = call_fetch_sequences(rsat_service, bed_filecontent, args.genome[0])
  File "/home/BioApps/ExoProfiler/20150821/00_matrixScanWS/matrixScanWS.py", line 155, in call_fetch_sequences
    result = service.fetch_sequences(arguments_fetch)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 542, in **call**
    return client.invoke(args, kwargs)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 637, in send
    reply = transport.send(request)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/transport/https.py", line 64, in send
    return  HttpTransport.send(self, request)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/transport/http.py", line 77, in send
    fp = self.u2open(u2request)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/transport/http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "/home/u0855942/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/home/u0855942/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/home/u0855942/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/home/u0855942/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/u0855942/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/home/u0855942/lib/python2.7/httplib.py", line 1067, in getresponse
    response.begin()
  File "/home/u0855942/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/home/u0855942/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/u0855942/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out

**Comment by morganeTC** [comment]
Hello,

The matrix-scan step (performed in matrixScanWS.py) wraps a call to a
remote server, which I guess is either down or encountering network
issues. Could you check in the code which server is it pointing to ?

Best regards,

Morgane

**Comment by terooatt** [comment]
It looks like the RSAT server was down but it is working now and I am getting a new error. I am using the input and the matrix in transfac format from the paper as shown below
Thank you.
[u0643357@hci-alta Exoprofiler_project]$ nohup /home/BioApps/ExoProfiler/20150821/00_matrixScanWS/matrixScanWS.py -b input_ctcf.bed --genome hg19 --matrix_file matrix_Paper --uth_pval 0.001 -o CTCFEXOprofiler.out &> nohup.out &

&gt;hg19_chrY_58991314_58991314_+
C
&gt;hg19_chrY_58993329_58993329_+
T
&gt;hg19_chrY_58993959_58993959_+
C
&gt;hg19_chrY_58996518_58996518_+
C
&gt;hg19_chrY_59003045_59003045_+
A
&gt;hg19_chrY_59013130_59013130_+
C
&gt;hg19_chrY_59018666_59018666_+
T
&gt;hg19_chrY_59019771_59019771_+
T
&gt;hg19_chrY_59028039_59028039_+
A
</sequence>
            <matrix>AC  MA0035.3
XX
ID  Gata1
XX
DE  MA0035.3 Gata1; from JASPAR
PO       A     C     G     T
1     2035  4321  2530  9069
2      506  6406  2792  8251
3        0 14869   437  2649
4        0   697     0 17258
5        0     0     0 17955
6    17955     0     0     0
7        0     0     0 17955
8        0 17955     0     0
9     2166     0     0 15789
10    2502  6166  6687  2600
11    1886  5072  1598  9399
XX
CC  program: jaspar
CC  matrix.nb: 169
XX
MA0035.3.tf 

</matrix>
            <matrix_format>transfac</matrix_format>
            <quick>1</quick>
            <n_treatment>score</n_treatment>
            <pseudo>1</pseudo>
            <background_input>1</background_input>
            <markov>1</markov>
            <background_pseudo>0.01</background_pseudo>
            <uth>pval 0.001</uth>
            <str>2</str>
            <origin>start</origin>
         </request>
      /ns1:matrix_scan
   /ns0:Body
/SOAP-ENV:Envelope
Traceback (most recent call last):
  File "/home/BioApps/ExoProfiler/20150821/00_matrixScanWS/matrixScanWS.py", line 323, in <module>
    result = call_matrix_scan(rsat_service, fasta_content, matrix, args.uth_pval[0])
  File "/home/BioApps/ExoProfiler/20150821/00_matrixScanWS/matrixScanWS.py", line 260, in call_matrix_scan
    result = service.matrix_scan(arguments)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 542, in **call**
    return client.invoke(args, kwargs)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 649, in send
    result = self.failed(binding, e)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 702, in failed
    r, p = binding.get_fault(reply)
  File "/home/u0855942/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/bindings/binding.py", line 265, in get_fault
    raise WebFault(p, faultroot)
suds.WebFault: Server raised fault: 'Execution error: Error
    Error with the expected frequency file : the sum must be strictly positive  0
Illegal division by zero at /data/rsat/perl-scripts/lib//RSAT/MarkovModel.pm line 878.
command: &RSAT::util::hide_RSAT_path(/data/rsat/perl-scripts/matrix-scan -i '/data/rsat/public_html/tmp/www-data/2015/08/24/matrix-scan-sequence_2015-08-24.231358_PGY9lO' -m '/data/rsat/public_html/tmp/www-data/2015/08/24/matrix-scan-matrix_2015-08-24.231358_X3iw9l' -matrix_format 'transfac' -quick -n score -pseudo '1' -bginput -markov '1' -bg_pseudo '0.01' -uth 'pval' '0.001' -2str)'

**Comment by terooatt** [comment]
HI here is the URL that seem to create the timeout socket. http://pedagogix-tagc.univ-mrs.fr/rsat/web_services/RSATWS.wsdl

**Comment by morganeTC** [comment]
The URL seems fine this morning, could you check again ?

If the problem persists, while we enquire about it, you can also change
the URL in the code, since we have other entry points for RSAT web
services (used by matrixScanWS.py):

http://rsat01.biologie.ens.fr/rsat/web_services/RSATWS.wsdl

**Comment by ibn-salem** [comment]
The matrixScanWS.py script uses this URL for RSAT:
 [http://pedagogix-tagc.univ-mrs.fr/rsat/](http://pedagogix-tagc.univ-mrs.fr/rsat/)
It works fine for me in the moment. Please report if there are problems again.
