### ISSUE TITLE
problem with ExoProfiler

### ISSUE THREAD

**Issue by robeach78** [ComputationalSystemsBiology/ExoProfiler#2]
the site that is listed on your script matrixScanWS.py: "http://rsat.ulb.ac.be/rsat" 

does not exit anymore...

which one would you propose to substitute it?

I am getting this error:

Traceback (most recent call last):
  File "../00_matrixScanWS/matrixScanWS.py", line 371, in <module>
    result = call_compare_matrices_2sets(rsat_service, matrix, one_perm_matrix, Ncor_threshold)
  File "../00_matrixScanWS/matrixScanWS.py", line 218, in call_compare_matrices_2sets
    return perform_compare_matrices(service, arguments_comp)
  File "../00_matrixScanWS/matrixScanWS.py", line 197, in perform_compare_matrices
    b = numpy.genfromtxt(urllib2.urlopen(url_to_download), delimiter='\t', names=True, dtype=None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by robeach78** [comment]
and this step does not work for the permutated sequences. I guess because it needs a server tool that is no longer available on that URL you provided on the script...

**Comment by ibn-salem** [comment]
Thanks for reporting this. I replaced the URL. Please check if it works for you now!
