### ISSUE TITLE
error

### ISSUE THREAD

**Issue by robeach78** [ComputationalSystemsBiology/ExoProfiler#4]
trying to run the program with a matrix that yesterday worked and today no more....

Traceback (most recent call last):
  File "../00_matrixScanWS/matrixScanWS.py", line 306, in <module>
    fasta_content = call_fetch_sequences(rsat_service, bed_filecontent, args.genome[0])
  File "../00_matrixScanWS/matrixScanWS.py", line 156, in call_fetch_sequences
    result = service.fetch_sequences(arguments_fetch)
  File "/Library/Python/2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "/Library/Python/2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/Library/Python/2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 637, in send
    reply = transport.send(request)
  File "/Library/Python/2.7/site-packages/suds-0.4-py2.7.egg/suds/transport/https.py", line 64, in send
    return  HttpTransport.send(self, request)
  File "/Library/Python/2.7/site-packages/suds-0.4-py2.7.egg/suds/transport/http.py", line 77, in send
    fp = self.u2open(u2request)
  File "/Library/Python/2.7/site-packages/suds-0.4-py2.7.egg/suds/transport/http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out
INFO: Read 0 of 0 input regions.
INFO: Begin to parse reads from BAM file for n=0 regions.
INFO: Finished parsing of BAM file.
Traceback (most recent call last):
  File "../01_5primeCounter/5PrimeCounter.py", line 506, in <module>
    consensus = get_consensus(regions, "motif_seq")
  File "../01_5primeCounter/5PrimeCounter.py", line 331, in get_consensus
    counts = np.zeros(( m, 5 ), np.int )
ValueError: negative dimensions are not allowed
INFO: Read 0 of 0 input regions.
INFO: Begin to parse reads from BAM file for n=0 regions.
INFO: Finished parsing of BAM file.
Traceback (most recent call last):
  File "../01_5primeCounter/5PrimeCounter.py", line 506, in <module>
    consensus = get_consensus(regions, "motif_seq")
  File "../01_5primeCounter/5PrimeCounter.py", line 331, in get_consensus
    counts = np.zeros(( m, 5 ), np.int )
ValueError: negative dimensions are not allowed
INFO: Read 0 of 0 input regions.
INFO: Begin to parse reads from BAM file for n=0 regions.
INFO: Finished parsing of BAM file.
INFO: Begin to fetch sequences....
INFO: Finished sequences.
[1] "output_NR3C2c_5PrimeCounter_wperm" "perm"                             
[1] FALSE
[1] TRUE
Error in read.table(paste(prefix, ".up_counts.tab", sep = ""), header = FALSE,  : 
  no lines available in input
Calls: as.matrix -> read.table
Execution halted
[1] "output_NR3C2c_5PrimeCounter"
[1] FALSE
[1] FALSE
Error in read.table(paste(prefix, ".up_counts.tab", sep = ""), header = FALSE,  : 
  no lines available in input
Calls: as.matrix -> read.table
Execution halted
[1] "output_NR3C2c_5PrimeCounter_wgenome" "genome_seq"                         
[1] TRUE
[1] FALSE
Error in read.table(paste(prefix, ".up_counts.tab", sep = ""), header = FALSE,  : 
  no lines available in input
Calls: as.matrix -> read.table
Execution halted

**Comment by rsa-tools** [comment]
Is it still not working ? The program relies on Web services that may have been down at the moment you tested.

**Comment by ibn-salem** [comment]
This seems to be a temporary problem with the web-service of RSAT. See #1
