### ISSUE TITLE
 Exoprofiler erro socket.timeout: timed out

### ISSUE THREAD

**Issue by sudhirjadhao** [ComputationalSystemsBiology/ExoProfiler#5]
I am trying to calculate  chip-exo coverage from my chip seq data .

Motif Database I have used is jaspar_core_nonredundant_vertebrates_2016.tf

Command used:
python ~/Tools/ExoProfiler-master/00_matrixScanWS/matrixScanWS.py --bed_file $1 --genome hg19 --matrix_file $2 --uth_pval 0.001 --output_file Matrixscan_out/$out"_"$out2/output_matrix_scan_0-001.txt --perm
Error log 

MatrixScanWS started for :
Traceback (most recent call last):
  File "/home/sjadhao/Tools/ExoProfiler-master/00_matrixScanWS/matrixScanWS.py", line 324, in <module>
    result = call_matrix_scan(rsat_service, fasta_content, matrix, args.uth_pval[0])
  File "/home/sjadhao/Tools/ExoProfiler-master/00_matrixScanWS/matrixScanWS.py", line 261, in call_matrix_scan
    result = service.matrix_scan(arguments)
  File "build/bdist.linux-x86_64/egg/suds/client.py", line 542, in __call__
  File "build/bdist.linux-x86_64/egg/suds/client.py", line 602, in invoke
  File "build/bdist.linux-x86_64/egg/suds/client.py", line 637, in send
  File "build/bdist.linux-x86_64/egg/suds/transport/https.py", line 64, in send
  File "build/bdist.linux-x86_64/egg/suds/transport/http.py", line 77, in send
  File "build/bdist.linux-x86_64/egg/suds/transport/http.py", line 118, in u2open
  File "/home/sjadhao/anaconda2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/sjadhao/anaconda2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/sjadhao/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/sjadhao/anaconda2/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/sjadhao/anaconda2/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/home/sjadhao/anaconda2/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/home/sjadhao/anaconda2/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/home/sjadhao/anaconda2/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/sjadhao/anaconda2/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out

Can you pleas help me to solve above error ?

Thank you Inadvance

**Comment by ibn-salem** [comment]
Thanks for reporting this. This seems to be a temporary problem with the RSAT web-service. See #1.
It should work now.
