### ISSUE TITLE
ValueError: start out of range (-1)

### ISSUE THREAD

**Issue by sudhirjadhao** [ComputationalSystemsBiology/ExoProfiler#6]
Command used:
python ~/Tools/ExoProfiler-master/01_5primeCounter/5primeCounter.py --input_sites Matrixscan_out/$out"_"$out2/output_matrix_scan_0-001.txt --bam_file $3  --output_prefix 5PrimeCounter_output/$out"_"$out2/$out"_"$out2 --genome_seq ~/Database/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa  --output_seq --perm

Error log:
INFO: Read 1610 of 1610 input regions.
INFO: Begin to parse reads from BAM file for n=1610 regions.
Traceback (most recent call last):
  File "/home/sjadhao/Tools/ExoProfiler-master/01_5primeCounter/5primeCounter.py", line 480, in <module>
    regions = reads_profile(regions, args.bam_file, args.size)
  File "/home/sjadhao/Tools/ExoProfiler-master/01_5primeCounter/5primeCounter.py", line 196, in reads_profile
    for aln in bamHandle[ iv ]:
  File "/home/sjadhao/.local/lib/python2.7/site-packages/HTSeq-0.6.1-py2.7-linux-x86_64.egg/HTSeq/__init__.py", line 978, in __getitem__
    for pa in self.sf.fetch( iv.chrom, iv.start+1, iv.end ):
  File "pysam/calignmentfile.pyx", line 897, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:10997)
  File "pysam/calignmentfile.pyx", line 825, in pysam.calignmentfile.AlignmentFile.parse_region (pysam/calignmentfile.c:10563)
ValueError: start out of range (-1)

Can you please help me to solve above erro?

Thank you Inadvance

**Comment by ibn-salem** [comment]
Dear @sudhirjadhao,
thanks for reporting this. I think the problem here is that an input region close to chromosome start is extended by +-30bp in 5primeCounter.py . This creates a GenomicIntreval object with start position < 0, that cause this error.
